<?php

$fck_toolsbars = array(
	'fichier'=>array(
		'nom'=>'fichiers',
		'barres'=>array(
			'full'=>array(
				'nom'=>'complète',
				'barre'=>"['Source','DocProps','-','Save','NewPage','Templates','-','Preview','Print']"
			),
			'light'=>array(
				'nom'=>'allégée',
				'barre'=>"['Source','Save','NewPage','-','Preview','Print']"
			),
			'extralight'=>array(
				'nom'=>'très allégé', 
				'barre'=>"['Source','Preview']"
			)
		)
	),
	'copie'=>array(
		'nom'=>'copie',
		'barres'=>array(
			'full'=>array(
				'nom'=>'complète',
				'barre'=>"['Cut','Copy','Paste','PasteText','PasteWord']"
			),
			'light'=>array(
				'nom'=>'allégée',
				'barre'=>"['Cut','Copy','Paste']"
			)
		)
	),
	'outils'=>array(
		'nom'=>'outils',
		'barres'=>array(
			'full'=>array(
				'nom'=>'complète',
				'barre'=>"['Undo','Redo','-','Find','Replace','-','SelectAll','RemoveFormat'],'/'"
			),
			'light'=>array(
				'nom'=>'allégée',
				'barre'=>"['Undo','Redo','-','Find','Replace']"
			)
		)
	),
	'miseenforme'=>array(
		'nom'=>'mise en forme',
		'barres'=>array(
			'full'=>array(
				'nom'=>'complète',
				'barre'=>"['Bold','Italic','Underline','StrikeThrough','-','Subscript','Superscript','-','TextColor','BGColor','-','SpecialChar']"
			),
			'light'=>array(
				'nom'=>'allégée',
				'barre'=>"['Bold','Italic','Underline','StrikeThrough','-','Subscript','Superscript','-','SpecialChar']"
			)
		)
	),
	'blocs'=>array(
		'nom'=>'blocs',
		'barres'=>array(
			'full'=>array(
				'nom'=>'complète',
				'barre'=>"['JustifyLeft','JustifyCenter','JustifyRight','JustifyFull','-','OrderedList','UnorderedList','-','Table','Rule','-'],['Outdent','Indent','Blockquote','CreateDiv']"
			),
			'light'=>array(
				'nom'=>'allégée',
				'barre'=>"['JustifyLeft','JustifyCenter','JustifyRight','JustifyFull','-','OrderedList','UnorderedList','-','Table','Rule','-','Outdent','Indent']"
			),
			'extralight'=>array(
				'nom'=>'très allégée',
				'barre'=>"['JustifyLeft','JustifyCenter','JustifyRight','JustifyFull','-','OrderedList','UnorderedList','-','Table','Rule']"
			)
		)
	),
	'liens'=>array(
		'nom'=>'liens',
		'barres'=>array(
			'full'=>array(
				'nom'=>'complète',
				'barre'=>"['Link','SpipLink','Unlink','Anchor']"
			),
			'spip'=>array(
				'nom'=>'SPIP',
				'barre'=>"['SpipLink','Unlink']"
			)
		)
	),
	'images'=>array(
		'nom'=>'images',
		'barres'=>array(
			'full'=>array(
				'nom'=>'complète',
				'barre'=>"['SpipImg','Image','imgmapPopup','Smiley']"
			),
			'spip'=>array(
				'nom'=>'SPIP',
				'barre'=>"['SpipImg','imgmapPopup','Smiley']"
			),
			'spiplight'=>array(
				'nom'=>'SPIP seulement',
				'barre'=>"['SpipImg']"
			)
		)
	),
	'documents'=>array(
		'nom'=>'documents',
		'barres'=>array(
			'full'=>array(
				'nom'=>'complète',
				'barre'=>"['SpipDoc','Flash']"
			),
			'light'=>array(
				'nom'=>'SPIP',
				'barre'=>"['SpipDoc']"
			)
		)
	),
	'caracteres'=>array(
		'nom'=>'styles',
		'barres'=>array(
			'full'=>array(
				'nom'=>'complète',
				'barre'=>"'/',['Style','FontFormat','-'],['FontName','FontSize']"
			),
			'light'=>array(
				'nom'=>'allégée',
				'barre'=>"['FontFormat','FontName','FontSize']"
			),
			'extralight'=>array(
				'nom'=>'très allégée',
				'barre'=>"['FontSize']"
			)
		)
	),
	'editeur'=>array(
		'nom'=>'éditeur',
		'barres'=>array(
			'full'=>array(
				'nom'=>'complète',
				'barre'=>"['FitWindow','ShowBlocks','-','About']"
			),
			'apropos'=>array(
				'nom'=>'à propos',
				'barre'=>"['About']"
			)
		)
	)			
) ;



 ?>
